baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "fr"
title = "Mon grenier"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
enableRobotsTXT = true
enableEmoji = true

[params]
	author = "Timothee Decoster"
	description = "My first blog."
	avatar = "/img/avatar.jpg"
	enableToc = true
	enableShareCard = true
	favicon = "/img/defaultFav.ico"
  
  	#Background settings
	enableColorBG= false
	bgBlur = "0px"
	bgImage = "/img/matrix.jpg"
  
	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji = true

[social]
	email = "decostertimoth@gmail.com"
	github = "timothee-decoster"
	siteStartYear = 2018
